### ISSUE TITLE
Container exits with segfault

### ISSUE THREAD

**Issue by dirickxmaarten** [Stuermer/EchelleSimulator#17]
Trying to run the container on dockers exits after downloading the fits file. Upon closer inspection I noticed that running echellesimulator with the params provided in the example, crashes the simulator.

> root@718253d05be1:/home/build#` ./echellesimulator --spectrograph MaroonX --phoenix 3500,-1.,0.,5.5,1 -r 100 -o mdwarf.fits
>Spectrograph file found: ../data/spectrographs/MaroonX.hdf
>Read in 33 Orders
>
>Iterating over elements in the file
>Simulating phoenix spectra with magnitude = 1
>Trying to download PHOENIX Spectrum with: T_eff=3500 log_g=5.5 z=-1 Alpha=0
>Downloading spectra from: ftp://phoenix.astro.physik.uni-goettingen.de/HiResFITS/PHOENIX-ACES-AGSS-COND-2011/Z-1.0/lte03500-5.50-1.0.PHOENIX-ACES-AGSS-COND-2011-HiRes.fits
>Segmentation fault (core dumped)`

**Comment by Stuermer** [comment]
Thanks for reporting it and sorry for the delay in replying.
The problem was missing directories for the downloaded phoenix spectra... (data/phoenix_spectra)

I believe I have fixed it, I updated the docker image. I appreciate if you confirm. 

p.s. I'm working on a python version just FYI. No promises on when this will happen though.

**Comment by Stuermer** [comment]
I'll close the issue, since I believe it's fixed. If you still experience problems don't hesitate to reopen the issue. Thanks.

**Comment by dirickxmaarten** [comment]
Yes indeed, the issue is resolved. Thank you for the update!
Kind regards,
Maarten
